export interface Product {
  id: string
  title: string
  icon: string
  tagline: string
  description: string
  industries: string[]
  regions: string[]
  status: string
  lifecycleStage: string
  personas: string[]
  image: string
}

export const allProducts: Product[] = [
  {
    id: "planning-law-chatbot",
    title: "Planning Law Chatbot",
    icon: "FileText",
    tagline: "Instant planning regulations at your fingertips",
    description: "Enter a plot location and get allowable use, maximum height, floor area ratio, and sanitary requirements instantly. Outputs a formatted feasibility PDF ready for client meetings.",
    industries: ["Architecture Firms", "Real Estate Developers"],
    regions: ["Middle East", "Sri Lanka", "UK"],
    status: "Scaling",
    lifecycleStage: "Feasibility",
    personas: ["architects", "real-estate-developers"],
    image: "/images/perk-health.png",
  },
  {
    id: "cost-plan-calculator",
    title: "Cost Plan Calculator + Financial Management",
    icon: "Calculator",
    tagline: "GFA to budget in minutes. Not days.",
    description: "Upload a concept drawing. Get the Gross Floor Area, project cost, and consultancy fee automatically — with a financial planning module built in.",
    industries: ["Real Estate Developers", "QS Firms"],
    regions: ["UAE", "UK", "Australia", "Sri Lanka"],
    status: "Pre-design",
    lifecycleStage: "Feasibility",
    personas: ["real-estate-developers", "construction-consultancies"],
    image: "/images/perk-vacation.png",
  },
  {
    id: "hand-drawn-to-autocad",
    title: "Hand Drawn to AutoCAD",
    icon: "PencilRuler",
    tagline: "Your sketches become clean CAD files",
    description: "Photograph your hand-drawn floor plan and receive a clean CAD file. The tool learns your specific drawing style and handwriting over time — accuracy improves with every project.",
    industries: ["Architects", "Modelling Firms"],
    regions: ["UK", "Australia"],
    status: "Scaling",
    lifecycleStage: "Architecture & Modelling",
    personas: ["architects", "modellers"],
    image: "/images/perk-parental.png",
  },
  {
    id: "auto-conversion-2d-to-3d",
    title: "Auto Conversion 2D to 3D",
    icon: "Box",
    tagline: "2D drawings to 3D BIM models automatically",
    description: "Computer vision reads your 2D PDF drawing and converts elements directly into a 3D BIM model — no modeller needed. The only complete AI-automated PDF-to-3D product available.",
    industries: ["Architecture Firms", "Structural Modellers"],
    regions: ["Australia"],
    status: "Custom / R&D",
    lifecycleStage: "Architecture & Modelling",
    personas: ["architects", "modellers"],
    image: "/images/perk-retirement.png",
  },
  {
    id: "wordtobim",
    title: "WordtoBIM",
    icon: "MessageSquare",
    tagline: "Describe a building, get a 3D model",
    description: "Describe a building element or layout in plain text and the 3D model is generated from your words. Pulls live planning and regulatory information into the modelling session automatically.",
    industries: ["Architecture Firms", "Modelling Firms"],
    regions: ["Universal"],
    status: "Custom / R&D",
    lifecycleStage: "Architecture & Modelling",
    personas: ["architects", "modellers"],
    image: "/images/perk-setup.png",
  },
  {
    id: "quanto-revit",
    title: "Quanto for Revit",
    icon: "Layers",
    tagline: "BOQ from Revit models, AI rate prediction",
    description: "Quanto reads your Revit model and returns a priced BOQ. AI rate prediction from your firm's pricing history. Hours not weeks.",
    industries: ["QS Firms", "Cost Consultancies"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    lifecycleStage: "BOQ Preparation",
    personas: ["construction-consultancies"],
    image: "/images/perk-wellbeing.png",
  },
  {
    id: "quanto-acc",
    title: "Quanto for ACC",
    icon: "BarChart3",
    tagline: "BOQ from ACC, repriced as the design changes",
    description: "Quanto connects to Autodesk Construction Cloud and generates a priced BOQ. Reprices automatically as the design changes. No export step.",
    industries: ["QS Firms", "Cloud-First Practices"],
    regions: ["UK", "Australia"],
    status: "Scaling",
    lifecycleStage: "BOQ Preparation",
    personas: ["construction-consultancies"],
    image: "/images/value-kind.png",
  },
  {
    id: "quanto-costx",
    title: "Quanto for CostX",
    icon: "BarChart3",
    tagline: "BOQ from CostX workbooks, AI rate prediction",
    description: "Quanto reads your CostX workbook and adds AI rate prediction on top. Priced BOQ without the manual rate lookup.",
    industries: ["QS Firms", "Cost Consultancies"],
    regions: ["UK", "Australia", "UAE"],
    status: "Scaling",
    lifecycleStage: "BOQ Preparation",
    personas: ["construction-consultancies"],
    image: "/images/perk-parental.png",
  },
  {
    id: "quanto-2d",
    title: "Quanto for 2D Drawings",
    icon: "FileSearch",
    tagline: "BOQ from flat drawings, no 3D model needed",
    description: "Quanto reads a 2D PDF or DXF drawing and returns a priced BOQ. No 3D model needed. Computer vision identifies elements from flat drawings.",
    industries: ["Contractors", "QS Firms"],
    regions: ["Middle East", "Sri Lanka", "Australia"],
    status: "Custom / R&D",
    lifecycleStage: "BOQ Preparation",
    personas: ["contractors", "construction-consultancies"],
    image: "/images/value-mission.png",
  },
  {
    id: "costx-to-boq",
    title: "CostX to BOQ",
    icon: "BarChart3",
    tagline: "Client-ready BOQ straight from your CostX workbooks",
    description: "Reads your dimension groups and workbook data, maps them to NRM2 or your client's template, and produces a priced BOQ in minutes.",
    industries: ["QS Firms", "Cost Consultancies", "Contractors"],
    regions: ["Middle East", "Sri Lanka", "Australia"],
    status: "Available",
    lifecycleStage: "BOQ Preparation",
    personas: ["construction-consultancies", "contractors"],
    image: "/images/perk-parental.png",
  },
  {
    id: "auto-reinforcement",
    title: "Auto Reinforcement Plugin",
    icon: "Wrench",
    tagline: "Complete reinforcement schedules, zero manual steps",
    description: "Computer vision reads rebar notations, lengths, spans, and radii directly from structural drawings. AI agents generate the complete reinforcement schedule automatically.",
    industries: ["Contractors", "QS Consultancies"],
    regions: ["UAE", "Australia"],
    status: "Custom / R&D",
    lifecycleStage: "BOQ Preparation",
    personas: ["contractors", "construction-consultancies"],
    image: "/images/value-pace.png",
  },
  {
    id: "tender-evaluations",
    title: "Tender Evaluations",
    icon: "Scale",
    tagline: "Bid comparison reports from supplier emails",
    description: "Automatically downloads emails from suppliers and bidders and extracts pricing data for evaluation. Produces a side-by-side bid comparison report ready for the award decision.",
    industries: ["Contractors", "Builders"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    lifecycleStage: "Tendering",
    personas: ["contractors"],
    image: "/images/value-truth.png",
  },
  {
    id: "buildmarketlk",
    title: "BuildMarketlk.com",
    icon: "Store",
    tagline: "Construction marketplace for suppliers and subcontractors",
    description: "Searchable marketplace of material suppliers, builders, and subcontractors. Displays average construction prices so you can benchmark supplier quotes without calling around.",
    industries: ["Contractors", "Builders", "Suppliers"],
    regions: ["Sri Lanka", "Global Licensing"],
    status: "Scaling",
    lifecycleStage: "Tendering",
    personas: ["contractors"],
    image: "/images/buildmarketlk_dashboard.png",
  },
  {
    id: "buildmonitor",
    title: "BuildMonitor Mobile App",
    icon: "Hammer",
    tagline: "Daily progress reports that write themselves",
    description: "Site personnel record progress on mobile — photos, quantities, activities. Daily Progress Report generates automatically in your contract's required format. No additional input needed.",
    industries: ["Contractors", "Builders"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    lifecycleStage: "Construction Stage",
    personas: ["contractors"],
    image: "/images/learnmore-hero-bg.png",
  },
  {
    id: "measureonair",
    title: "MeasureonAir",
    icon: "Ruler",
    tagline: "From site measurement to payment certificate digitally",
    description: "Record measurements directly against the digital drawing on site — no printed plans. Payment applications and interim certificates generate automatically from the recorded measurements.",
    industries: ["Contractors", "Construction Consultancies"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    lifecycleStage: "Construction Stage",
    personas: ["contractors", "construction-consultancies"],
    image: "/images/perk-health.png",
  },
  {
    id: "prelim",
    title: "Prelim",
    icon: "ClipboardList",
    tagline: "Task, attendance & productivity for QS teams",
    description: "Run your QS team from one platform: create and assign work, track time and attendance, chat with your team where the work lives, and benchmark planned against actual productivity in real time.",
    industries: ["QS Consultancies", "Cost Management Firms"],
    regions: ["Sri Lanka", "Middle East", "Australia"],
    status: "Available",
    lifecycleStage: "Construction Stage",
    personas: ["construction-consultancies", "contractors"],
    image: "/images/perk-wellbeing.png",
  },
  {
    id: "builderbot",
    title: "BuilderBot.ai",
    icon: "BrainCircuit",
    tagline: "FIDIC-trained AI that reads contracts, models, and records together",
    description: "FIDIC-trained legal AI that returns clause-referenced answers. Upload 3D models alongside contract documents — ask questions that span models, contracts, and project records simultaneously.",
    industries: ["Construction Legal", "Consulting Firms"],
    regions: ["UAE", "Global"],
    status: "Scaling",
    lifecycleStage: "Claims & Legal Disputes",
    personas: ["legal-professionals"],
    image: "/images/perk-retirement.png",
  }
]
