export interface Product {
  id: string
  title: string
  icon: string
  tagline: string
  description: string
  industries: string[]
  regions: string[]
  status: string
  personas: string[]
  image: string
}

export const allProducts: Product[] = [
  {
    id: "planning-law-chatbot",
    title: "Planning Law Chatbot",
    icon: "FileText",
    tagline: "Instant planning regulations at your fingertips",
    description: "Enter a plot location and get allowable use, maximum height, floor area ratio, and sanitary requirements instantly. Outputs a formatted feasibility PDF ready for client meetings.",
    industries: ["Architecture Firms", "Real Estate Developers"],
    regions: ["Middle East", "Sri Lanka", "UK"],
    status: "Scaling",
    personas: ["architects", "real-estate-developers"],
    image: "/images/perk-health.png",
  },
  {
    id: "hand-drawn-to-autocad",
    title: "Hand Drawn to AutoCAD",
    icon: "PencilRuler",
    tagline: "Your sketches become clean CAD files",
    description: "Photograph your hand-drawn floor plan and receive a clean CAD file. The tool learns your specific drawing style and handwriting over time — accuracy improves with every project.",
    industries: ["Architects", "Modelling Firms"],
    regions: ["UK", "Australia"],
    status: "Scaling",
    personas: ["architects", "modellers"],
    image: "/images/perk-parental.png",
  },
  {
    id: "auto-conversion-2d-to-3d",
    title: "Auto Conversion 2D to 3D",
    icon: "Box",
    tagline: "2D drawings to 3D BIM models automatically",
    description: "Computer vision reads your 2D PDF drawing and converts elements directly into a 3D BIM model — no modeller needed. The only complete AI-automated PDF-to-3D product available.",
    industries: ["Architecture Firms", "Structural Modellers"],
    regions: ["Australia"],
    status: "Custom / R&D",
    personas: ["architects", "modellers"],
    image: "/images/perk-retirement.png",
  },
  {
    id: "wordtobim",
    title: "WordtoBIM",
    icon: "MessageSquare",
    tagline: "Describe a building, get a 3D model",
    description: "Describe a building element or layout in plain text and the 3D model is generated from your words. Pulls live planning and regulatory information into the modelling session automatically.",
    industries: ["Architecture Firms", "Modelling Firms"],
    regions: ["Universal"],
    status: "Custom / R&D",
    personas: ["architects", "modellers"],
    image: "/images/perk-setup.png",
  },
  {
    id: "cost-plan-calculator",
    title: "Cost Plan Calculator + Financial Management",
    icon: "Calculator",
    tagline: "GFA to budget in minutes. Not days.",
    description: "Upload a concept drawing. Get the Gross Floor Area, project cost, and consultancy fee automatically — with a financial planning module built in.",
    industries: ["Real Estate Developers", "QS Firms"],
    regions: ["UAE", "UK", "Australia", "Sri Lanka"],
    status: "Pre-design",
    personas: ["real-estate-developers", "construction-consultancies"],
    image: "/images/perk-vacation.png",
  },
  {
    id: "revit-to-boq",
    title: "Revit to BOQ Plugin",
    icon: "Layers",
    tagline: "Automated BOQ generation from Revit models",
    description: "Identifies all building elements from Revit take-off files and generates a standard BOQ automatically. AI predicts rates for each line item — existing tools stop at measurement.",
    industries: ["QS Firms", "Cost Consultancies"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    personas: ["construction-consultancies"],
    image: "/images/perk-wellbeing.png",
  },
  {
    id: "acc-to-boq",
    title: "Autodesk CC to BOQ",
    icon: "BarChart3",
    tagline: "Cloud-native BOQ from Autodesk Construction Cloud",
    description: "Same BOQ automation as the Revit plugin, built natively for Autodesk Construction Cloud — no export step. Automatically reprices when the design proposal changes.",
    industries: ["QS Firms", "Cloud-First Practices"],
    regions: ["UK", "Australia"],
    status: "Scaling",
    personas: ["construction-consultancies"],
    image: "/images/value-kind.png",
  },
  {
    id: "2d-drawing-to-boq",
    title: "2D Drawing to BOQ",
    icon: "FileSearch",
    tagline: "BOQ from flat drawings — no 3D model needed",
    description: "Reads a 2D PDF structural drawing, identifies building elements using computer vision, and produces a priced BOQ. The only BOQ automation tool that operates from flat drawings alone.",
    industries: ["Contractors", "QS Firms"],
    regions: ["Middle East", "Sri Lanka", "Australia"],
    status: "Custom / R&D",
    personas: ["contractors", "construction-consultancies"],
    image: "/images/value-mission.png",
  },
  {
    id: "auto-reinforcement",
    title: "Auto Reinforcement Plugin",
    icon: "Wrench",
    tagline: "Complete reinforcement schedules, zero manual steps",
    description: "Computer vision reads rebar notations, lengths, spans, and radii directly from structural drawings. AI agents generate the complete reinforcement schedule automatically.",
    industries: ["Contractors", "QS Consultancies"],
    regions: ["UAE", "Australia"],
    status: "Custom / R&D",
    personas: ["contractors", "construction-consultancies"],
    image: "/images/value-pace.png",
  },
  {
    id: "tender-evaluations",
    title: "Tender Evaluations",
    icon: "Scale",
    tagline: "Bid comparison reports from supplier emails",
    description: "Automatically downloads emails from suppliers and bidders and extracts pricing data for evaluation. Produces a side-by-side bid comparison report ready for the award decision.",
    industries: ["Contractors", "Builders"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    personas: ["contractors"],
    image: "/images/value-truth.png",
  },
  {
    id: "buildmonitor",
    title: "BuildMonitor Mobile App",
    icon: "Hammer",
    tagline: "Daily progress reports that write themselves",
    description: "Site personnel record progress on mobile — photos, quantities, activities. Daily Progress Report generates automatically in your contract's required format. No additional input needed.",
    industries: ["Contractors", "Builders"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    personas: ["contractors"],
    image: "/images/learnmore-hero-bg.png",
  },
  {
    id: "measureonair",
    title: "MeasureonAir",
    icon: "Ruler",
    tagline: "From site measurement to payment certificate digitally",
    description: "Record measurements directly against the digital drawing on site — no printed plans. Payment applications and interim certificates generate automatically from the recorded measurements.",
    industries: ["Contractors", "Construction Consultancies"],
    regions: ["Middle East", "Sri Lanka"],
    status: "Scaling",
    personas: ["contractors", "construction-consultancies"],
    image: "/images/perk-health.png",
  },
  {
    id: "erp-automations",
    title: "ERP Automations",
    icon: "Cog",
    tagline: "Bridge the gap between site and back office",
    description: "Email instructions automatically converted into ERP job cards. Site app data syncs directly to the ERP, eliminating the lag between field activity and financial records.",
    industries: ["Real Estate Developers", "Contractors"],
    regions: ["Global"],
    status: "Scaling",
    personas: ["real-estate-developers", "contractors"],
    image: "/images/perk-parental.png",
  },
  {
    id: "builderbot",
    title: "BuilderBot.ai",
    icon: "BrainCircuit",
    tagline: "FIDIC-trained AI that reads contracts, models, and records together",
    description: "FIDIC-trained legal AI that returns clause-referenced answers. Upload 3D models alongside contract documents — ask questions that span models, contracts, and project records simultaneously.",
    industries: ["Construction Legal", "Consulting Firms"],
    regions: ["UAE", "Global"],
    status: "Scaling",
    personas: ["legal-professionals"],
    image: "/images/perk-retirement.png",
  },
  {
    id: "buildmarketlk",
    title: "BuildMarketlk.com",
    icon: "Store",
    tagline: "Construction marketplace for suppliers and subcontractors",
    description: "Searchable marketplace of material suppliers, builders, and subcontractors. Displays average construction prices so you can benchmark supplier quotes without calling around.",
    industries: ["Contractors", "Builders", "Suppliers"],
    regions: ["Sri Lanka", "Global Licensing"],
    status: "Scaling",
    personas: ["contractors"],
    image: "/images/buildmarketlk_dashboard.png",
  },
]
